# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('udate', models.DateField(max_length=50, verbose_name='用户生日')),
                ('uemail', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
        ),
    ]
