# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.IntegerField(default=0, verbose_name='角色Id'),
        ),
    ]
