# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_users_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role_name',
            field=models.CharField(default='', max_length=10, verbose_name='角色名称'),
        ),
    ]
