# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-21 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_users_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ugender',
            field=models.CharField(default='', max_length=2, verbose_name='用户性别'),
        ),
    ]
