# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_users_ugender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=5, verbose_name='出生省份')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='province_id',
            field=models.IntegerField(default=0, verbose_name='省份Id'),
        ),
    ]
